version: 0.2

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh -channel LTS
  build:
    commands:
      - echo "dotnet installed"
      - dotnet --info
artifacts:
  type: zip
  paths:
    - '*'
