version: 0.2

phases:
  install:
    commands:
      - ./dotnet-install.ps1 -Channel LTS
  build:
    commands:
      - echo "dotnet installed"
      - dotnet publish -o C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\
artifacts:
  type: zip
  paths:
    - '*'
