version: 0.2

phases:
  install:
    commands:
      - ./dotnet-install.ps1 -Channel LTS
  build:
    commands:
      - Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where { $_.PSChildName -Match '^(?!S)\p{L}'} | Select PSChildName, version
artifacts:
  type: zip
  paths:
    - '*'
