version: 0.2

phases:
  install:
    commands:
#      - ./dotnet-install.ps1 -Channel LTS
       - ./dotnet-install.ps1 -Runtime dotnet -Version 6.0.0
  build:
    commands:
      - echo "dotnet installed"
 #     - cd C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\
 #     - dotnet publish -o C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\artifact
artifacts:
  type: zip
  paths:
    - '*'
