version: 0.2

phases:
  install:
    commands:
     - ./dotnet-install.ps1
  build:
    commands:
      - echo "dotnet installed"
      - dotnet --info
 #     - cd C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\
 #     - dotnet publish -o C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\artifact
artifacts:
  type: zip
  paths:
    - '*'
